#!/bin/bash

compteur=$#

while ! pareil $compteur 0 

do 

if est-option ${!compteur}

then
	compteur=$(expr $compteur - 1)
else

	resultat="$resultat $(echo $* |  cut -d " " -f$compteur)"

	compteur=$(expr $compteur - 1)

fi

done
echo $resultat


